apiVersion: v1
kind: Secret
metadata:
  name: frontend-wd-jwt
  namespace: default
data:
  kongCredType: and0
  key: ZnJvbnRlbmQtd2Qtand0
  algorithm: SFMyNTY=
  secret: ZnJvbnRlbmQtd2Qtand0LXNlY3JldA==
type: Opaque
